<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title' => 'Panduan Lengkap Membangun Website',
                'author' => 'Andi Wijaya',
                'isbn' => '978-602-0000-01-1',
                'publisher' => 'Media Digital',
                'published_year' => 2023,
                'category' => 'Teknologi',
                'description' => 'Buku panduan praktis membangun website dari nol hingga tayang, cocok untuk pemula tanpa latar belakang teknis. Dilengkapi contoh dan studi kasus nyata.',
                'pages' => 320,
                'price' => 125000,
                'stock' => 20,
                'weight_gram' => 450,
                'sort_order' => 1,
            ],
            [
                'title' => 'Dasar-Dasar Desain Grafis',
                'author' => 'Rina Kartika',
                'isbn' => '978-602-0000-02-8',
                'publisher' => 'Kreatif Pustaka',
                'published_year' => 2022,
                'category' => 'Desain',
                'description' => 'Pengantar dunia desain grafis: tipografi, warna, komposisi, dan prinsip visual. Panduan ideal bagi calon desainer maupun pelaku UMKM.',
                'pages' => 260,
                'price' => 95000,
                'stock' => 15,
                'weight_gram' => 380,
                'sort_order' => 2,
            ],
            [
                'title' => 'Strategi Pemasaran Digital Modern',
                'author' => 'Bagus Prakoso',
                'isbn' => '978-602-0000-03-5',
                'publisher' => 'Bisnis Media',
                'published_year' => 2024,
                'category' => 'Bisnis',
                'description' => 'Membahas strategi pemasaran digital terkini: media sosial, SEO, iklan berbayar, dan analitik. Praktis dan mudah diterapkan untuk berbagai skala usaha.',
                'pages' => 300,
                'price' => 145000,
                'stock' => 10,
                'weight_gram' => 420,
                'sort_order' => 3,
            ],
            [
                'title' => 'Menulis Konten yang Menjual',
                'author' => 'Sari Melati',
                'isbn' => '978-602-0000-04-2',
                'publisher' => 'Media Digital',
                'published_year' => 2023,
                'category' => 'Bisnis',
                'description' => 'Teknik copywriting untuk website, media sosial, dan iklan. Belajar menyusun kalimat yang menarik perhatian dan mendorong tindakan.',
                'pages' => 240,
                'price' => 89000,
                'stock' => 12,
                'weight_gram' => 350,
                'sort_order' => 4,
            ],
            [
                'title' => 'Fotografi Produk untuk Pemula',
                'author' => 'Dimas Aditya',
                'isbn' => '978-602-0000-05-9',
                'publisher' => 'Kreatif Pustaka',
                'published_year' => 2022,
                'category' => 'Fotografi',
                'description' => 'Panduan memotret produk dengan peralatan sederhana agar tampak profesional. Cocok untuk penjual online dan pelaku bisnis kecil.',
                'pages' => 180,
                'price' => 75000,
                'stock' => 30,
                'weight_gram' => 300,
                'sort_order' => 5,
            ],
            [
                'title' => 'Manajemen Proyek Praktis',
                'author' => 'Yusuf Hakim',
                'isbn' => '978-602-0000-06-6',
                'publisher' => 'Bisnis Media',
                'published_year' => 2021,
                'category' => 'Manajemen',
                'description' => 'Prinsip dan alat manajemen proyek yang mudah diterapkan oleh tim kecil maupun besar. Dilengkapi template dan contoh alur kerja.',
                'pages' => 220,
                'price' => 98000,
                'stock' => 25,
                'weight_gram' => 340,
                'sort_order' => 6,
            ],
            [
                'title' => 'Belajar Pemrograman dari Nol',
                'author' => 'Fajar Nugraha',
                'isbn' => '978-602-0000-07-3',
                'publisher' => 'Media Digital',
                'published_year' => 2024,
                'category' => 'Teknologi',
                'description' => 'Pengantar logika pemrograman dan bahasa modern untuk pemula. Disusun dengan bahasa sederhana dan latihan bertahap.',
                'pages' => 360,
                'price' => 135000,
                'stock' => 18,
                'weight_gram' => 500,
                'sort_order' => 7,
            ],
            [
                'title' => 'Produktivitas Tanpa Stres',
                'author' => 'Maya Anjani',
                'isbn' => '978-602-0000-08-0',
                'publisher' => 'Inspira Pustaka',
                'published_year' => 2023,
                'category' => 'Pengembangan Diri',
                'description' => 'Metode praktis mengatur waktu dan energi agar lebih produktif tanpa kelelahan. Berisi kebiasaan kecil yang berdampak besar.',
                'pages' => 200,
                'price' => 79000,
                'stock' => 22,
                'weight_gram' => 320,
                'sort_order' => 8,
            ],
            [
                'title' => 'Dasar Analitik Data untuk Bisnis',
                'author' => 'Reza Pratama',
                'isbn' => '978-602-0000-09-7',
                'publisher' => 'Bisnis Media',
                'published_year' => 2022,
                'category' => 'Bisnis',
                'description' => 'Memahami data untuk pengambilan keputusan bisnis yang lebih tepat. Membahas metrik penting dan cara membacanya secara sederhana.',
                'pages' => 280,
                'price' => 115000,
                'stock' => 8,
                'weight_gram' => 400,
                'sort_order' => 9,
            ],
            [
                'title' => 'Membangun Brand yang Kuat',
                'author' => 'Laras Wulandari',
                'isbn' => '978-602-0000-10-3',
                'publisher' => 'Inspira Pustaka',
                'published_year' => 2024,
                'category' => 'Bisnis',
                'description' => 'Langkah membangun identitas brand yang konsisten dan berkesan. Dari logo hingga suara brand, dijelaskan secara menyeluruh.',
                'pages' => 250,
                'price' => 105000,
                'stock' => 14,
                'weight_gram' => 380,
                'sort_order' => 10,
            ],
            [
                'title' => 'Panduan Media Sosial untuk Organisasi',
                'author' => 'Nina Safitri',
                'isbn' => '978-602-0000-11-0',
                'publisher' => 'Media Digital',
                'published_year' => 2023,
                'category' => 'Bisnis',
                'description' => 'Strategi mengelola media sosial organisasi agar tumbuh dan aktif. Berisi tips membuat konten, jadwal posting, dan interaksi komunitas.',
                'pages' => 210,
                'price' => 85000,
                'stock' => 16,
                'weight_gram' => 330,
                'sort_order' => 11,
            ],
            [
                'title' => 'Keamanan Digital Sehari-hari',
                'author' => 'Arif Setiawan',
                'isbn' => '978-602-0000-12-7',
                'publisher' => 'Media Digital',
                'published_year' => 2024,
                'category' => 'Teknologi',
                'description' => 'Praktik menjaga keamanan akun, data, dan privasi di dunia digital. Panduan mudah dipahami untuk semua kalangan.',
                'pages' => 190,
                'price' => 88000,
                'stock' => 20,
                'weight_gram' => 310,
                'sort_order' => 12,
            ],
        ];

        foreach ($books as $book) {
            Book::firstOrCreate(
                ['slug' => Str::slug($book['title'])],
                array_merge($book, ['slug' => Str::slug($book['title']), 'is_available' => true])
            );
        }
    }
}
