<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title' => 'Riyadhus Shalihin',
                'author' => 'Imam An-Nawawi',
                'isbn' => '978-602-6534-01-1',
                'publisher' => 'Gema Insani',
                'published_year' => 2020,
                'category' => 'Hadits',
                'description' => 'Kitab hadits pilihan yang memuat hadits-hadits sahih tentang adab, akhlak, dan ibadah sehari-hari. Disusun oleh Imam An-Nawawi rahimahullah dengan sistematika yang mudah dipahami.',
                'pages' => 640,
                'price' => 125000,
                'stock' => 20,
                'weight_gram' => 750,
                'sort_order' => 1,
            ],
            [
                'title' => 'Bulughul Maram',
                'author' => 'Ibnu Hajar Al-Asqalani',
                'isbn' => '978-602-6534-02-8',
                'publisher' => 'Pustaka Imam Syafi\'i',
                'published_year' => 2021,
                'category' => 'Hadits',
                'description' => 'Kumpulan hadits hukum yang menjadi referensi utama fiqih. Dilengkapi takhrij dan keterangan derajat hadits oleh Ibnu Hajar Al-Asqalani.',
                'pages' => 520,
                'price' => 95000,
                'stock' => 15,
                'weight_gram' => 600,
                'sort_order' => 2,
            ],
            [
                'title' => 'Fiqih Islam Wa Adillatuhu Jilid 1',
                'author' => 'Dr. Wahbah Az-Zuhaili',
                'isbn' => '978-602-6534-03-5',
                'publisher' => 'Gema Insani',
                'published_year' => 2019,
                'category' => 'Fiqih',
                'description' => 'Ensiklopedia fiqih terlengkap karya Dr. Wahbah Az-Zuhaili. Membahas seluruh aspek ibadah dan muamalah dengan dalil-dalil yang kuat dari Al-Qur\'an dan Sunnah.',
                'pages' => 780,
                'price' => 145000,
                'stock' => 10,
                'weight_gram' => 900,
                'sort_order' => 3,
            ],
            [
                'title' => 'Tafsir Ibnu Katsir Jilid 1',
                'author' => 'Ibnu Katsir',
                'isbn' => '978-602-6534-04-2',
                'publisher' => 'Darul Haq',
                'published_year' => 2022,
                'category' => 'Tafsir',
                'description' => 'Tafsir Al-Qur\'an paling populer di dunia Islam. Diterjemahkan secara lengkap dan akurat dari bahasa Arab ke bahasa Indonesia dengan gaya bahasa yang mudah dipahami.',
                'pages' => 700,
                'price' => 135000,
                'stock' => 12,
                'weight_gram' => 820,
                'sort_order' => 4,
            ],
            [
                'title' => 'Kitab At-Tauhid',
                'author' => 'Syaikh Muhammad bin Abdul Wahhab',
                'isbn' => '978-602-6534-05-9',
                'publisher' => 'Pustaka Arafah',
                'published_year' => 2020,
                'category' => 'Aqidah',
                'description' => 'Kitab tauhid yang wajib dipelajari oleh setiap muslim. Membahas hakikat tauhid, pembagiannya, serta hal-hal yang dapat merusak kemurnian tauhid.',
                'pages' => 320,
                'price' => 55000,
                'stock' => 30,
                'weight_gram' => 380,
                'sort_order' => 5,
            ],
            [
                'title' => 'Aqidah Wasithiyyah',
                'author' => 'Syaikhul Islam Ibnu Taimiyyah',
                'isbn' => '978-602-6534-06-6',
                'publisher' => 'Dar Ibn Hazm',
                'published_year' => 2021,
                'category' => 'Aqidah',
                'description' => 'Risalah singkat namun padat tentang aqidah Ahlus Sunnah wal Jama\'ah. Disertai syarah dan penjelasan dari ulama kontemporer.',
                'pages' => 180,
                'price' => 45000,
                'stock' => 25,
                'weight_gram' => 220,
                'sort_order' => 6,
            ],
            [
                'title' => 'Matan Al-Ajrumiyyah',
                'author' => 'Ibnu Ajrum',
                'isbn' => '978-602-6534-07-3',
                'publisher' => 'Penerbit Toobagus',
                'published_year' => 2018,
                'category' => 'Nahwu & Sharaf',
                'description' => 'Kitab teks nahwu (tata bahasa Arab) paling populer untuk pemula. Disajikan dengan matan dan syarah yang mudah dipahami oleh pelajar pemula.',
                'pages' => 96,
                'price' => 25000,
                'stock' => 40,
                'weight_gram' => 120,
                'sort_order' => 7,
            ],
            [
                'title' => 'Alfiyah Ibnu Malik',
                'author' => 'Ibnu Malik',
                'isbn' => '978-602-6534-08-0',
                'publisher' => 'Darul Haq',
                'published_year' => 2019,
                'category' => 'Nahwu & Sharaf',
                'description' => 'Kitab nadhom (puisi) yang memuat seribu bait tentang kaidah nahwu dan sharaf. Menjadi acuan utama dalam pengajaran bahasa Arab di pesantren seluruh dunia.',
                'pages' => 240,
                'price' => 65000,
                'stock' => 18,
                'weight_gram' => 280,
                'sort_order' => 8,
            ],
            [
                'title' => 'Ihya Ulumuddin Jilid 1',
                'author' => 'Imam Al-Ghazali',
                'isbn' => '978-602-6534-09-7',
                'publisher' => 'Pustaka Imam Syafi\'i',
                'published_year' => 2020,
                'category' => 'Akhlak',
                'description' => 'Masterpiece karya Imam Al-Ghazali yang membahas tentang ilmu agama, ibadah, adat kebiasaan, dan jalan menuju keselamatan. Menjadi rujukan utama tasawuf sunni.',
                'pages' => 680,
                'price' => 115000,
                'stock' => 8,
                'weight_gram' => 800,
                'sort_order' => 9,
            ],
            [
                'title' => 'Tazkiyatun Nafs',
                'author' => 'Ibnu Rajab Al-Hanbali',
                'isbn' => '978-602-6534-10-3',
                'publisher' => 'Pustaka Arafah',
                'published_year' => 2022,
                'category' => 'Akhlak',
                'description' => 'Panduan lengkap penyucian jiwa dan pembentukan akhlak mulia. Membahas penyakit-penyakit hati dan cara mengobatinya berdasarkan Al-Qur\'an dan Sunnah.',
                'pages' => 350,
                'price' => 75000,
                'stock' => 22,
                'weight_gram' => 420,
                'sort_order' => 10,
            ],
            [
                'title' => 'Al-Wajiz Fi Ushul Fiqih',
                'author' => 'Dr. Abdul Karim Zaidan',
                'isbn' => '978-602-6534-11-0',
                'publisher' => 'Gema Insani',
                'published_year' => 2021,
                'category' => 'Fiqih',
                'description' => 'Buku ushul fiqih yang ringkas namun komprehensif. Cocok sebagai pengantar bagi mahasiswa dan santri yang ingin memahami metodologi istinbath hukum Islam.',
                'pages' => 420,
                'price' => 85000,
                'stock' => 14,
                'weight_gram' => 500,
                'sort_order' => 11,
            ],
            [
                'title' => 'Zad Al-Maad Jilid 1',
                'author' => 'Ibnu Qayyim Al-Jauziyyah',
                'isbn' => '978-602-6534-12-7',
                'publisher' => 'Dar Ibn Hazm',
                'published_year' => 2020,
                'category' => 'Hadits',
                'description' => 'Kitab sirah nabawiyah dan panduan hidup Islami. Membahas petunjuk Nabi Muhammad ﷺ dalam berbagai aspek kehidupan.',
                'pages' => 580,
                'price' => 105000,
                'stock' => 10,
                'weight_gram' => 680,
                'sort_order' => 12,
            ],
            [
                'title' => 'Mukhtashar Minhajul Qashidin',
                'author' => 'Ibnu Qudamah Al-Maqdisi',
                'isbn' => '978-602-6534-13-4',
                'publisher' => 'Penerbit Toobagus',
                'published_year' => 2023,
                'category' => 'Akhlak',
                'description' => 'Ringkasan dari kitab Minhajul Qashidin yang membahas jalan menuju keselamatan. Ditulis dengan gaya bahasa yang lebih sederhana dan mudah dipahami.',
                'pages' => 280,
                'price' => 58000,
                'stock' => 16,
                'weight_gram' => 340,
                'sort_order' => 13,
            ],
            [
                'title' => 'Tafsir As-Sa\'di Jilid 1',
                'author' => 'Syaikh As-Sa\'di',
                'isbn' => '978-602-6534-14-1',
                'publisher' => 'Darul Haq',
                'published_year' => 2022,
                'category' => 'Tafsir',
                'description' => 'Tafsir kontemporer yang mudah dipahami dengan bahasa yang lugas dan tidak bertele-tele. Sangat cocok untuk pembaca yang ingin memahami makna Al-Qur\'an.',
                'pages' => 620,
                'price' => 120000,
                'stock' => 9,
                'weight_gram' => 730,
                'sort_order' => 14,
            ],
            [
                'title' => 'Shahih Fiqih Sunnah Jilid 1',
                'author' => 'Abu Malik Kamal',
                'isbn' => '978-602-6534-15-8',
                'publisher' => 'Pustaka Imam Syafi\'i',
                'published_year' => 2021,
                'category' => 'Fiqih',
                'description' => 'Ensiklopedia fiqih yang menggabungkan antara kajian hadits dan hukum fiqih secara komprehensif. Dilengkapi derajat hadits untuk setiap dalil yang digunakan.',
                'pages' => 700,
                'price' => 130000,
                'stock' => 11,
                'weight_gram' => 820,
                'sort_order' => 15,
            ],
        ];

        foreach ($books as $book) {
            Book::firstOrCreate(
                ['slug' => Str::slug($book['title'])],
                array_merge($book, ['slug' => Str::slug($book['title']), 'is_available' => true])
            );
        }
    }
}
